//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public int KeyId { get; set; }
        public string ProcessorId { get; set; }
        public string SymfoniaUser { get; set; }
        public string eMail { get; set; }
        public int CompanyId { get; set; }
        public System.DateTime StartDay { get; set; }
        public Nullable<System.DateTime> ExpirationDay { get; set; }
        public int LicenceId { get; set; }
    
        public virtual Companies Companies { get; set; }
        public virtual Keys Keys { get; set; }
        public virtual Licence Licence { get; set; }
    }
}
